export const STATUS_IDLE = 'STATUS_IDLE';
export const STATUS_ACTIVE = 'STATUS_ACTIVE';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_ERROR = 'STATUS_ERROR';
export const STATUS_RESETTING = 'STATUS_RESETTING';
